"""empty message

Revision ID: a77f4ee516bd
Revises: 3fe1f821f2aa
Create Date: 2021-02-03 10:19:16.002894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a77f4ee516bd'
down_revision = '3fe1f821f2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.Text(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
